### PR TITLE
regenerate

### PR DESCRIPTION
**Pull request by turbomam**
- #16

### CODE REVIEW

**Review by aclum — CHANGES_REQUESTED** [review]
I can't find some of new envo terms in in the nmdco-classes.json. 'stream water' ENVO:03605006 or 'freshwater stream biome' ENVO:03605008. Are those expected in the json or I'm looking at the wrong file.

**Comment by turbomam** [comment]
> I can't find some of new envo terms in in the nmdco-classes.json. 'stream water' ENVO:03605006 or 'freshwater stream biome' ENVO:03605008. Are those expected in the json or I'm looking at the wrong file.

Thanks @aclum. I'm going to merge this and make a release, and watch to see if Bioportal updates their records.

**Comment by turbomam** [comment]
@aclum "stream water" is in `nmdco-classes.json` now

**Comment by turbomam** [comment]
I have also added some QC reports

**Pull request merged**
